apiVersion: v1
kind: Service
metadata:
  name: signoz-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/component: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      nodePort: 30317
    - name: otlp-http
      port: 4318
      targetPort: 4318
      nodePort: 30318
